program Emissor_Nfe;

uses
  Forms,
  Windows,
  Dialogs,
  System.SysUtils,
  principal in 'fnts\principal.pas' {frmPrincipal},
  modulo in '..\FNTS_Gerencial\fnts\modulo.pas' {frmmodulo: TDataModule},
  splash in '..\FNTS_Comuns\splash.pas' {frmsplash},
  setor in '..\FNTS_Gerencial\fnts\setor.pas' {frmSetor},
  loc_setor in '..\FNTS_Gerencial\fnts\loc_setor.pas' {frmloc_setor},
  loc_grupo_servico in '..\FNTS_Gerencial\fnts\loc_grupo_servico.pas' {frmloc_grupo_servico},
  convenio in '..\FNTS_Gerencial\fnts\convenio.pas' {frmconvenio},
  funcionario in '..\FNTS_Gerencial\fnts\funcionario.pas' {frmfuncionario},
  contacorrente in '..\FNTS_Gerencial\fnts\contacorrente.pas' {frmcontacorrente},
  banco in '..\FNTS_Gerencial\fnts\banco.pas' {frmbanco},
  cheque_avulso in '..\FNTS_Gerencial\fnts\cheque_avulso.pas' {frmcheque_avulso},
  condpgto in '..\FNTS_Gerencial\fnts\condpgto.pas' {frmcondpgto},
  aliquota in '..\FNTS_Gerencial\fnts\aliquota.pas' {frmAliquota},
  loc_regiao in '..\FNTS_Gerencial\fnts\loc_regiao.pas' {frmloc_regiao},
  loc_receita in '..\FNTS_Gerencial\fnts\loc_receita.pas' {frmloc_receita},
  loc_aliquota in '..\FNTS_Gerencial\fnts\loc_aliquota.pas' {frmloc_aliquota},
  loc_conta in '..\FNTS_Gerencial\fnts\loc_conta.pas' {frmloc_conta},
  loc_cfop in '..\FNTS_Gerencial\fnts\loc_cfop.pas' {frmloc_cfop},
  webcam in '..\FNTS_Gerencial\fnts\webcam.pas' {frmwebcam},
  plano in '..\FNTS_Gerencial\fnts\plano.pas' {frmplano},
  fornecedor in '..\FNTS_Gerencial\fnts\fornecedor.pas' {frmfornecedor},
  produto_saida_item in '..\FNTS_Gerencial\fnts\produto_saida_item.pas' {frmproduto_saida_item},
  loc_cliente_VENDA in '..\FNTS_Gerencial\fnts\loc_cliente_VENDA.pas' {frmloc_cliente_VENDA},
  produto_preco in '..\FNTS_Gerencial\fnts\produto_preco.pas' {frmproduto_preco},
  produto_grade_saida in '..\FNTS_Gerencial\fnts\produto_grade_saida.pas' {frmproduto_grade_saida},
  produto_serial_entrada in '..\FNTS_Gerencial\fnts\produto_serial_entrada.pas' {frmproduto_serial_entrada},
  caixa_operador in '..\FNTS_Gerencial\fnts\caixa_operador.pas' {frmCaixa_operador},
  produto_pedido in '..\FNTS_Gerencial\fnts\produto_pedido.pas' {frmproduto_pedido},
  produto_pedido_item in '..\FNTS_Gerencial\fnts\produto_pedido_item.pas' {frmproduto_pedido_item},
  produto_grade_pedido in '..\FNTS_Gerencial\fnts\produto_grade_pedido.pas' {frmproduto_grade_pedido},
  produto_serialF in '..\FNTS_Gerencial\fnts\produto_serialF.pas' {frmproduto_serialF},
  notafiscalE in '..\FNTS_Gerencial\fnts\notafiscalE.pas' {frmnotafiscalE},
  notafiscalE_item in '..\FNTS_Gerencial\fnts\notafiscalE_item.pas' {frmnotafiscalE_item},
  empresa in '..\FNTS_Gerencial\fnts\empresa.pas' {frmempresa},
  loc_transportador in '..\FNTS_Gerencial\fnts\loc_transportador.pas' {frmloc_transportador},
  loc_fornecedor in '..\FNTS_Gerencial\fnts\loc_fornecedor.pas' {frmLoc_fornecedor},
  Cheque_baixa in '..\FNTS_Gerencial\fnts\Cheque_baixa.pas' {frmcheque_baixa},
  cliente_veiculo in '..\FNTS_Gerencial\fnts\cliente_veiculo.pas' {frmcliente_veiculo},
  contacorrente_lancamento2 in '..\FNTS_Gerencial\fnts\contacorrente_lancamento2.pas' {frmcontacorrente_lancamento2},
  contacorrente_ficha in '..\FNTS_Gerencial\fnts\contacorrente_ficha.pas' {frmcontacorrente_ficha},
  loc_contacorrent in '..\FNTS_Gerencial\fnts\loc_contacorrent.pas' {frmloc_contacorrente},
  loc_banco in '..\FNTS_Gerencial\fnts\loc_banco.pas' {frmloc_banco},
  contacorrente_lancamento in '..\FNTS_Gerencial\fnts\contacorrente_lancamento.pas' {frmcontacorrente_lancamento},
  servico in '..\FNTS_Gerencial\fnts\servico.pas' {frmservico},
  caixa_abertura_individual in '..\FNTS_Gerencial\fnts\caixa_abertura_individual.pas' {frmcaixa_abertura_individual},
  caixa_abertura in '..\FNTS_Gerencial\fnts\caixa_abertura.pas' {frmcaixa_abertura},
  caixa_fechamento in '..\FNTS_Gerencial\fnts\caixa_fechamento.pas' {frmcaixa_fechamento},
  caixa_ficha in '..\FNTS_Gerencial\fnts\caixa_ficha.pas' {frmcaixa_ficha},
  contaspagar in '..\FNTS_Gerencial\fnts\contaspagar.pas' {frmcontaspagar},
  contaspagar_fichaalteracao in '..\FNTS_Gerencial\fnts\contaspagar_fichaalteracao.pas' {frmcontaspagar_fichaAlteracao},
  contaspagar_ficha_entrada in '..\FNTS_Gerencial\fnts\contaspagar_ficha_entrada.pas' {frmcontaspagar_ficha_entrada},
  contaspagar_pgto in '..\FNTS_Gerencial\fnts\contaspagar_pgto.pas' {frmcontaspagar_pgto},
  contaspagar_cheque in '..\FNTS_Gerencial\fnts\contaspagar_cheque.pas' {frmcontaspagar_cheque},
  venda in '..\FNTS_Gerencial\fnts\venda.pas' {frmvenda},
  venda_inicio in '..\FNTS_Gerencial\fnts\venda_inicio.pas' {frmvenda_inicio},
  os_serial in '..\FNTS_Gerencial\fnts\os_serial.pas' {frmos_serial},
  venda_grade in '..\FNTS_Gerencial\fnts\venda_grade.pas' {frmvenda_grade},
  os_fechamento_auto in '..\FNTS_Gerencial\fnts\os_fechamento_auto.pas' {frmos_fechamento_auto},
  os_contasreceber_auto in '..\FNTS_Gerencial\fnts\os_contasreceber_auto.pas' {frmos_contasreceber_auto},
  troco in '..\FNTS_Gerencial\fnts\troco.pas' {frmvenda_troco},
  notas_venda_impressao in '..\FNTS_Gerencial\fnts\notas_venda_impressao.pas' {frmnotas_venda_impressao},
  venda_troca in '..\FNTS_Gerencial\fnts\venda_troca.pas' {frmvenda_troca},
  config_bobina in '..\FNTS_Gerencial\fnts\config_bobina.pas' {frmconfig_bobina},
  produto_etiqueta_codbarra in '..\FNTS_Gerencial\fnts\produto_etiqueta_codbarra.pas' {frmProduto_etiqueta_codbarra},
  contasreceber in '..\FNTS_Gerencial\fnts\contasreceber.pas' {frmcontasreceber},
  convenio_pgto in '..\FNTS_Gerencial\fnts\convenio_pgto.pas' {frmconvenio_pgto},
  contasreceber_banco in '..\FNTS_Gerencial\fnts\contasreceber_banco.pas' {frmContasreceber_banco},
  contasreceber_alterar in '..\FNTS_Gerencial\fnts\contasreceber_alterar.pas' {frmcontasreceber_alterar},
  contasreceber_ficha in '..\FNTS_Gerencial\fnts\contasreceber_ficha.pas' {frmcontasreceber_ficha},
  boleto_avulso in '..\FNTS_Gerencial\fnts\boleto_avulso.pas' {frmboleto_avulso},
  contasreceber_juros in '..\FNTS_Gerencial\fnts\contasreceber_juros.pas' {frmcontasreceber_juros},
  notas_venda in '..\FNTS_Gerencial\fnts\notas_venda.pas' {frmnotas_venda},
  os_impressao in '..\FNTS_Gerencial\fnts\os_impressao.pas' {frmos_impressao},
  os_ecf in '..\FNTS_Gerencial\fnts\os_ecf.pas' {frmos_ecf},
  os_auto in '..\FNTS_Gerencial\fnts\os_auto.pas' {frmOS_Auto},
  loc_veiculo in '..\FNTS_Gerencial\fnts\loc_veiculo.pas' {frmloc_veiculo},
  os_menu in '..\FNTS_Gerencial\fnts\os_menu.pas' {frmOs_menu},
  venda_serial in '..\FNTS_Gerencial\fnts\venda_serial.pas' {frmvenda_serial},
  cfop in '..\FNTS_Gerencial\fnts\cfop.pas' {frmcfop},
  loc_filial in '..\FNTS_Gerencial\fnts\loc_filial.pas' {frmloc_filial},
  prevenda_fechamento in '..\FNTS_Gerencial\fnts\prevenda_fechamento.pas' {frmprevenda_fechamento},
  prevenda_contasreceber in '..\FNTS_Gerencial\fnts\prevenda_contasreceber.pas' {frmprevenda_contasreceber},
  notafiscalE_impressao in '..\FNTS_Gerencial\fnts\notafiscalE_impressao.pas' {frmnotafiscalE_impressao},
  os_ecf_leituraMemoria in '..\FNTS_Gerencial\fnts\os_ecf_leituraMemoria.pas' {frmos_ecf_leituraMemoria},
  loc_convenio in '..\FNTS_Gerencial\fnts\loc_convenio.pas' {frmloc_convenio},
  logo in '..\FNTS_Gerencial\fnts\logo.pas' {frmlogo},
  orcamento_localizar in '..\FNTS_Gerencial\fnts\orcamento_localizar.pas' {frmOrcamento_localizar},
  produto_entrada in '..\FNTS_Gerencial\fnts\produto_entrada.pas' {frmproduto_entrada},
  produto_entrada_item in '..\FNTS_Gerencial\fnts\produto_entrada_item.pas' {frmproduto_entrada_item},
  loc_caixa in '..\FNTS_Gerencial\fnts\loc_caixa.pas' {frmloc_caixa},
  FmxUtils in '..\FNTS_Gerencial\fnts\FmxUtils.pas',
  cliente_financeiro in '..\FNTS_Gerencial\fnts\cliente_financeiro.pas' {frmcliente_financeiro},
  veiculo in '..\FNTS_Gerencial\fnts\veiculo.pas' {frmveiculo},
  os in '..\FNTS_Gerencial\fnts\os.pas' {frmos},
  os_fechamento in '..\FNTS_Gerencial\fnts\os_fechamento.pas' {frmos_fechamento},
  os_contasreceber in '..\FNTS_Gerencial\fnts\os_contasreceber.pas' {frmos_contasreceber},
  notas_venda_ecf in '..\FNTS_Gerencial\fnts\notas_venda_ecf.pas' {frmnotas_venda_ecf},
  notas_venda_ecf_leituraMemoria in '..\FNTS_Gerencial\fnts\notas_venda_ecf_leituraMemoria.pas' {frmnotas_venda_ecf_leituraMemoria},
  config_cobranca in '..\FNTS_Gerencial\fnts\config_cobranca.pas' {frmconfig_cobranca},
  contasreceber_duplicata in '..\FNTS_Gerencial\fnts\contasreceber_duplicata.pas' {frmcontasreceber_duplicata},
  contasreceber_tipoboleto in '..\FNTS_Gerencial\fnts\contasreceber_tipoboleto.pas' {frmcontasreceber_tipoboleto},
  contasreceber_cedente in '..\FNTS_Gerencial\fnts\contasreceber_cedente.pas' {frmcontasreceber_cedente},
  os_relatorio in '..\FNTS_Gerencial\fnts\os_relatorio.pas' {frmos_relatorio},
  sintegra_gerar in '..\FNTS_Comuns\sintegra_gerar.pas' {frmsintegra_gerar},
  Sintegra in '..\FNTS_Gerencial\fnts\Sintegra.pas',
  produto_importar in '..\FNTS_Gerencial\fnts\produto_importar.pas' {frmproduto_importar},
  produto_exportar in '..\FNTS_Gerencial\fnts\produto_exportar.pas' {frmproduto_exportar},
  usuario_menu in '..\FNTS_Gerencial\fnts\usuario_menu.pas' {frmusuario_menu},
  produto_total in '..\FNTS_Gerencial\fnts\produto_total.pas' {frmproduto_total},
  usuario in '..\FNTS_Gerencial\fnts\usuario.pas' {frmusuario},
  loc_cliente2 in '..\FNTS_Gerencial\fnts\loc_cliente2.pas' {frmloc_cliente2},
  contasreceber_ficha_varios in '..\FNTS_Gerencial\fnts\contasreceber_ficha_varios.pas' {frmcontasreceber_ficha_varios},
  loc_grupo in '..\FNTS_Gerencial\fnts\loc_grupo.pas' {frmloc_grupo},
  loc_subgrupo in '..\FNTS_Gerencial\fnts\loc_subgrupo.pas' {frmloc_subgrupo},
  loc_marca in '..\FNTS_Gerencial\fnts\loc_marca.pas' {frmloc_marca},
  lista_transportador2 in '..\FNTS_Gerencial\fnts\lista_transportador2.pas' {frmlista_transportador2},
  loc_cliente in '..\FNTS_Gerencial\fnts\loc_cliente.pas' {frmloc_cliente},
  xloc_funcionario in '..\FNTS_Gerencial\fnts\xloc_funcionario.pas' {frmxloc_Funcionario},
  lista_venda2 in '..\FNTS_Gerencial\fnts\lista_venda2.pas' {frmlista_venda2},
  lista_produto2 in '..\FNTS_Gerencial\fnts\lista_produto2.pas' {frmlista_produto2},
  extenso1 in '..\FNTS_Gerencial\fnts\extenso1.pas',
  xloc_cliente in '..\FNTS_Gerencial\fnts\xloc_cliente.pas' {frmxloc_cliente},
  lista_cliente2 in '..\FNTS_Gerencial\fnts\lista_cliente2.pas' {frmlista_cliente2},
  xloc_produto_entrada in '..\FNTS_Gerencial\fnts\xloc_produto_entrada.pas' {frmxloc_produto_entrada},
  xloc_banco in '..\FNTS_Gerencial\fnts\xloc_banco.pas' {frmxloc_banco},
  xloc_transportador in '..\FNTS_Gerencial\fnts\xloc_transportador.pas' {frmxloc_transportador},
  xloc_subgrupo in '..\FNTS_Gerencial\fnts\xloc_subgrupo.pas' {frmxloc_subgrupo},
  xloc_pessoas in '..\FNTS_Gerencial\fnts\xloc_pessoas.pas' {frmxloc_Pessoas},
  xloc_fornecedor in '..\FNTS_Gerencial\fnts\xloc_fornecedor.pas' {frmxloc_fornecedor},
  xloc_servico in '..\FNTS_Gerencial\fnts\xloc_servico.pas' {frmxloc_servico},
  xloc_empresa in '..\FNTS_Gerencial\fnts\xloc_empresa.pas' {frmxloc_empresa},
  xloc_gruposervico in '..\FNTS_Gerencial\fnts\xloc_gruposervico.pas' {frmxloc_gruposervico},
  lista_servicos_periodicos in '..\FNTS_Gerencial\fnts\lista_servicos_periodicos.pas' {frmlista_servicos_periodicos},
  processo in '..\FNTS_Gerencial\fnts\processo.pas' {frmprocesso},
  lista_servicos2 in '..\FNTS_Gerencial\fnts\lista_servicos2.pas' {frmlista_servicos2},
  lista_planocontas2 in '..\FNTS_Gerencial\fnts\lista_planocontas2.pas' {frmlista_planocontas2},
  xloc_grupo in '..\FNTS_Gerencial\fnts\xloc_grupo.pas' {frmxloc_grupo},
  lista_funcionario2 in '..\FNTS_Gerencial\fnts\lista_funcionario2.pas' {frmlista_funcionario2},
  lista_banco2 in '..\FNTS_Gerencial\fnts\lista_banco2.pas' {frmlista_banco2},
  venda_obs in '..\FNTS_Gerencial\fnts\venda_obs.pas' {frmvenda_obs},
  lista_caixa2 in '..\FNTS_Gerencial\fnts\lista_caixa2.pas' {frmlista_caixa2},
  lista_os in '..\FNTS_Gerencial\fnts\lista_os.pas' {frmlista_os},
  lista_cheque2 in '..\FNTS_Gerencial\fnts\lista_cheque2.pas' {frmlista_cheque2},
  notafiscal_item in '..\FNTS_Gerencial\fnts\notafiscal_item.pas' {frmnotafiscal_item},
  lista_pagar2 in '..\FNTS_Gerencial\fnts\lista_pagar2.pas' {frmlista_pagar2},
  xloc_notafiscal in '..\FNTS_Gerencial\fnts\xloc_notafiscal.pas' {frmxloc_notafiscal},
  contasreceber_impressao in '..\FNTS_Gerencial\fnts\contasreceber_impressao.pas' {frmcontasreceber_impressao},
  prevenda_impressao in '..\FNTS_Gerencial\fnts\prevenda_impressao.pas' {frmprevenda_impressao},
  Emitente in '..\FNTS_Gerencial\fnts\Emitente.pas' {frmemitente},
  config in '..\FNTS_Gerencial\fnts\config.pas' {frmconfig},
  xloc_conta in '..\FNTS_Gerencial\fnts\xloc_conta.pas' {frmxloc_CONTA},
  marca in '..\FNTS_Gerencial\fnts\marca.pas' {frmmarca},
  loc_funci_venda in '..\FNTS_Gerencial\fnts\loc_funci_venda.pas' {frmloc_funci_venda},
  venda_impressao2 in '..\FNTS_Gerencial\fnts\venda_impressao2.pas' {frmvenda_impressao2},
  balanca in '..\FNTS_Gerencial\fnts\balanca.pas' {frmbalanca},
  suprimentocaixa in '..\FNTS_Gerencial\fnts\suprimentocaixa.pas' {frmsuprimentocaixa},
  sangriacaixa in '..\FNTS_Gerencial\fnts\sangriacaixa.pas' {frmsangriacaixa},
  buscapreco in '..\FNTS_Gerencial\fnts\buscapreco.pas' {frmbuscapreco},
  lang in '..\FNTS_Gerencial\fnts\lang.pas',
  produto_atualizapreco in '..\FNTS_Gerencial\fnts\produto_atualizapreco.pas' {frmproduto_atualizapreco},
  xloc_veiculo in '..\FNTS_Gerencial\fnts\xloc_veiculo.pas' {frmxloc_veiculo},
  produto_consultapreco in '..\FNTS_Gerencial\fnts\produto_consultapreco.pas' {frmproduto_consultapreco},
  cheque_conta in '..\FNTS_Gerencial\fnts\cheque_conta.pas' {frmcheque_conta},
  lista_receber2 in '..\FNTS_Gerencial\fnts\lista_receber2.pas' {frmlista_receber2},
  produto_falta in '..\FNTS_Gerencial\fnts\produto_falta.pas' {frmproduto_falta},
  contaspagar_data in '..\FNTS_Gerencial\fnts\contaspagar_data.pas' {frmcontaspagar_data},
  convenio_receber in '..\FNTS_Gerencial\fnts\convenio_receber.pas' {frmconvenio_receber},
  contasreceber_pgto in '..\FNTS_Gerencial\fnts\contasreceber_pgto.pas' {frmcontasreceber_pgto},
  transportador in '..\FNTS_Gerencial\fnts\transportador.pas' {frmtransportador},
  xloc_cheque in '..\FNTS_Gerencial\fnts\xloc_cheque.pas' {frmxloc_cheque},
  cst in '..\FNTS_Gerencial\fnts\cst.pas' {frmcst},
  modelo_fiscal in '..\FNTS_Gerencial\fnts\modelo_fiscal.pas' {frmmodelo_fiscal},
  xloc_convenio in '..\FNTS_Gerencial\fnts\xloc_convenio.pas' {frmxloc_convenio},
  sintegra_menu in '..\FNTS_Gerencial\fnts\sintegra_menu.pas' {frmsintegra_menu},
  xloc_modelo in '..\FNTS_Gerencial\fnts\xloc_modelo.pas' {frmxloc_modelo},
  prevenda in '..\FNTS_Gerencial\fnts\prevenda.pas' {frmPrevenda},
  venda_fechamento in '..\FNTS_Comuns\venda_fechamento.pas' {frmvenda_fechamento},
  venda_contasreceber in '..\FNTS_Gerencial\fnts\venda_contasreceber.pas' {frmvenda_contasreceber},
  venda_nf in '..\FNTS_Gerencial\fnts\venda_nf.pas' {frmvenda_nf},
  produto_serial in '..\FNTS_Gerencial\fnts\produto_serial.pas' {frmproduto_serial},
  produto_gradeF in '..\FNTS_Gerencial\fnts\produto_gradeF.pas' {frmproduto_gradeF},
  produto_gradeFS in '..\FNTS_Gerencial\fnts\produto_gradeFS.pas' {frmproduto_gradeFS},
  compra in '..\FNTS_Gerencial\fnts\compra.pas' {frmcompra},
  compra_item in '..\FNTS_Gerencial\fnts\compra_item.pas' {frmcompra_item},
  notafiscal_menu in '..\FNTS_Comuns\notafiscal_menu.pas' {frmnotafiscal_menu},
  venda_impressao in '..\FNTS_Comuns\venda_impressao.pas' {frmvenda_impressao},
  etiqueta_grade in '..\FNTS_Gerencial\fnts\etiqueta_grade.pas' {frmetiqueta_grade},
  lista_fornecedor2 in '..\FNTS_Gerencial\fnts\lista_fornecedor2.pas' {frmlista_fornecedor2},
  lista_notaentrada in '..\FNTS_Gerencial\fnts\lista_notaentrada.pas' {frmlista_notaentrada},
  lista_entrada_sintegra in '..\FNTS_Gerencial\fnts\lista_entrada_sintegra.pas' {frmlista_entrada_sintegra},
  lista_notasaida in '..\FNTS_Gerencial\fnts\lista_notasaida.pas' {frmlista_notasaida},
  lista_pedcompra in '..\FNTS_Gerencial\fnts\lista_pedcompra.pas' {FRMLISTA_PEDCOMPRA},
  lista_notacompra in '..\FNTS_Gerencial\fnts\lista_notacompra.pas' {frmlista_notacompra},
  contasreceber_boleto in '..\FNTS_Gerencial\fnts\contasreceber_boleto.pas' {frmcontasreceber_boleto},
  compra_menu in '..\FNTS_Gerencial\fnts\compra_menu.pas' {frmcompra_menu},
  notafiscal in '..\FNTS_Comuns\notafiscal.pas' {frmnotafiscal},
  caixa in '..\FNTS_Gerencial\fnts\caixa.pas' {frmcaixa},
  cliente in '..\FNTS_Gerencial\fnts\cliente.pas' {frmcliente},
  venda_fechamento_especial in '..\FNTS_Gerencial\fnts\venda_fechamento_especial.pas' {frmvenda_fechamento_especial},
  mensagem_inventario in '..\FNTS_Gerencial\fnts\mensagem_inventario.pas' {frmmensagem_inventario},
  lista_autorizacao in '..\FNTS_Gerencial\fnts\lista_autorizacao.pas' {frmlista_autorizacao},
  grupo in '..\FNTS_Gerencial\fnts\grupo.pas' {frmgrupo},
  loc_materiaprima in '..\FNTS_Gerencial\fnts\loc_materiaprima.pas' {frmloc_materiaprima},
  produto_gradeI in '..\FNTS_Gerencial\fnts\produto_gradeI.pas' {frmproduto_gradeI},
  produto_rentabilidade in '..\FNTS_Gerencial\fnts\produto_rentabilidade.pas' {frmproduto_rentabilidade},
  etiquetador in '..\FNTS_Gerencial\fnts\etiquetador.pas' {frmetiquetador},
  notafiscal_impressao in '..\FNTS_Gerencial\fnts\notafiscal_impressao.pas' {frmnotafiscal_impressao},
  dados_inventario in '..\FNTS_Gerencial\fnts\dados_inventario.pas' {frmdados_inventario},
  os_servicosperiodicos in '..\FNTS_Gerencial\fnts\os_servicosperiodicos.pas' {frmos_servicosperiodicos},
  fornecedor_compras in '..\FNTS_Gerencial\fnts\fornecedor_compras.pas' {frmfornecedor_compras},
  lista_cliente_financeiro in '..\FNTS_Gerencial\fnts\lista_cliente_financeiro.pas' {frmlista_cliente_financeiro: venda_item_2},
  baixa_estoque in '..\FNTS_Gerencial\fnts\baixa_estoque.pas' {frmbaixa_estoque},
  orcamento in '..\FNTS_Gerencial\fnts\orcamento.pas' {frmOrcamento},
  orcamento_impressao in '..\FNTS_Gerencial\fnts\orcamento_impressao.pas' {frmorcamento_impressao},
  progresso in '..\FNTS_Gerencial\fnts\progresso.pas' {frmprogresso},
  dados_cliente in '..\FNTS_Gerencial\fnts\dados_cliente.pas' {frmdados_cliente},
  baixaestoque_impressao in '..\FNTS_Gerencial\fnts\baixaestoque_impressao.pas' {frmbaixaestoque_impressao},
  xloc_produto in '..\FNTS_Gerencial\fnts\xloc_produto.pas' {frmxloc_produto},
  venda_devolucao in '..\FNTS_Gerencial\fnts\venda_devolucao.pas' {frmvenda_devolucao},
  xloc_marca in '..\FNTS_Gerencial\fnts\xloc_marca.pas' {frmxloc_marca},
  grupo_servico in '..\FNTS_Gerencial\fnts\grupo_servico.pas' {frmgrupo_servico},
  produto in '..\FNTS_Gerencial\fnts\produto.pas' {frmproduto},
  xloc_cliente_veiculo in '..\FNTS_Gerencial\fnts\xloc_cliente_veiculo.pas' {frmxloc_cliente_veiculo},
  Produto_consultaserial in '..\FNTS_Gerencial\fnts\Produto_consultaserial.pas' {frmProduto_consultaserial},
  xloc_cfop in '..\FNTS_Gerencial\fnts\xloc_cfop.pas' {frmxloc_cfop},
  cheque_menu in '..\FNTS_Gerencial\fnts\cheque_menu.pas' {frmcheque_menu},
  cheque in '..\FNTS_Gerencial\fnts\cheque.pas' {frmcheque},
  produto_movimentar in '..\FNTS_Gerencial\fnts\produto_movimentar.pas' {frmproduto_movimentar},
  tamanho in '..\FNTS_Gerencial\fnts\tamanho.pas' {frmtamanho},
  receita in '..\FNTS_Gerencial\fnts\receita.pas' {frmreceita},
  cnae in '..\FNTS_Gerencial\fnts\cnae.pas' {frmCnae},
  venda_impressaoCP in '..\FNTS_Gerencial\fnts\venda_impressaoCP.pas' {frmvenda_impressaoCP},
  prevenda_nf_loja in '..\FNTS_Gerencial\fnts\prevenda_nf_loja.pas' {frmprevenda_nf_loja},
  prevenda_impressao_loja in '..\FNTS_Gerencial\fnts\prevenda_impressao_loja.pas' {frmprevenda_impressao_loja},
  prevenda_fechamento_loja in '..\FNTS_Gerencial\fnts\prevenda_fechamento_loja.pas' {frmprevenda_fechamento_loja},
  produto_foto in '..\FNTS_Gerencial\fnts\produto_foto.pas' {frmproduto_foto},
  notafiscal_cancelar in '..\FNTS_Gerencial\fnts\notafiscal_cancelar.pas' {frmnotafiscal_cancelar},
  contaspagar_nf in '..\FNTS_Gerencial\fnts\contaspagar_nf.pas' {frmcontaspagar_nf},
  contasreceber_renegociar in '..\FNTS_Gerencial\fnts\contasreceber_renegociar.pas' {frmcontasreceber_renegociar},
  contasreceber_recibo2 in '..\FNTS_Gerencial\fnts\contasreceber_recibo2.pas' {frmcontasreceber_recibo2},
  inventario in '..\FNTS_Gerencial\fnts\inventario.pas' {frmInventario},
  inventario_ficha in '..\FNTS_Gerencial\fnts\inventario_ficha.pas' {frminventario_ficha},
  produto_importanf in '..\FNTS_Gerencial\fnts\produto_importanf.pas' {frmproduto_importanf},
  loc_funci in '..\FNTS_Gerencial\fnts\loc_funci.pas' {frmloc_funci},
  produto_pdv2 in '..\FNTS_Gerencial\fnts\produto_pdv2.pas' {frmproduto_pdv2},
  nf_obs in '..\FNTS_Gerencial\fnts\nf_obs.pas' {frmnf_obs},
  entrega_ficha in '..\FNTS_Gerencial\fnts\entrega_ficha.pas' {frmEntrega_ficha},
  entrega in '..\FNTS_Gerencial\fnts\entrega.pas' {frmentrega},
  venda_entrega in '..\FNTS_Gerencial\fnts\venda_entrega.pas' {frmVenda_Entrega},
  contasreceber_recibo in '..\FNTS_Gerencial\fnts\contasreceber_recibo.pas' {frmcontasreceber_recibo},
  baixa_localizar in '..\FNTS_Gerencial\fnts\baixa_localizar.pas' {frmbaixa_localizar},
  lista_conhecimento in '..\FNTS_Gerencial\fnts\lista_conhecimento.pas' {frmlista_conhecimento},
  notafiscal_item2 in '..\FNTS_Comuns\notafiscal_item2.pas' {frmNotaFiscal_Item2},
  NotaFiscal_Item_grade in '..\FNTS_Gerencial\fnts\NotaFiscal_Item_grade.pas' {frmNotaFiscal_Item_grade},
  NotaFiscal_Item_serial in '..\FNTS_Gerencial\fnts\NotaFiscal_Item_serial.pas' {frmNotaFiscal_Item_Serial},
  copia_arquivo in '..\FNTS_Gerencial\fnts\copia_arquivo.pas' {frmcopia_arquivo},
  contaspagar_ficha in '..\FNTS_Gerencial\fnts\contaspagar_ficha.pas' {frmcontaspagar_ficha},
  venda_financeira in '..\FNTS_Gerencial\fnts\venda_financeira.pas' {frmvenda_financeira},
  financeira_ficha in '..\FNTS_Gerencial\fnts\financeira_ficha.pas' {frmfinanceira_ficha},
  financeira in '..\FNTS_Gerencial\fnts\financeira.pas' {frmFinanceira},
  financeira_pgto in '..\FNTS_Gerencial\fnts\financeira_pgto.pas' {frmFinanceira_Pgto},
  xloc_financeira in '..\FNTS_Gerencial\fnts\xloc_financeira.pas' {frmxloc_financeira},
  financeira_alterar in '..\FNTS_Gerencial\fnts\financeira_alterar.pas' {frmfinanceira_alterar},
  lista_financeira in '..\FNTS_Gerencial\fnts\lista_financeira.pas' {frmlista_financeira},
  orcamento_abrir in '..\FNTS_Gerencial\fnts\orcamento_abrir.pas' {frmOrcamento_Abrir},
  regiao in '..\FNTS_Gerencial\fnts\regiao.pas' {frmregiao},
  unNFe2 in '..\FNTS_Gerencial\fnts\unNFe2.pas',
  cliente_inicio in '..\FNTS_Gerencial\fnts\cliente_inicio.pas' {frmcliente_inicio},
  unFuncoesTEF in '..\FNTS_Gerencial\fnts\unFuncoesTEF.pas',
  msgcheque in '..\FNTS_Gerencial\fnts\msgcheque.pas' {frmmsgcheque},
  msgcartao in '..\FNTS_Gerencial\fnts\msgcartao.pas' {frmmsgcartao},
  unMensagem in '..\FNTS_Gerencial\fnts\unMensagem.pas' {frmMensagemTEF},
  Tef in '..\FNTS_Gerencial\fnts\Tef.pas' {frmTef},
  unCancelarTEF in '..\FNTS_Gerencial\fnts\unCancelarTEF.pas' {frmCancelarTEF},
  consulta_cheque in '..\FNTS_Gerencial\fnts\consulta_cheque.pas' {frmconsulta_cheque},
  cartao in '..\FNTS_Gerencial\fnts\cartao.pas' {frmCartao},
  cartao_alterar in '..\FNTS_Gerencial\fnts\cartao_alterar.pas' {frmcartao_alterar},
  cartao_ficha in '..\FNTS_Gerencial\fnts\cartao_ficha.pas' {frmcartao_ficha},
  cartao_pgto in '..\FNTS_Gerencial\fnts\cartao_pgto.pas' {frmCartao_PGTO},
  lista_cartao in '..\FNTS_Gerencial\fnts\lista_cartao.pas' {frmlista_cartao},
  xloc_cartao in '..\FNTS_Gerencial\fnts\xloc_cartao.pas' {frmxloc_cartao},
  produto_serial_ficha in '..\FNTS_Gerencial\fnts\produto_serial_ficha.pas' {frmProduto_serial_ficha},
  notafiscal_importacupom in '..\FNTS_Gerencial\fnts\notafiscal_importacupom.pas' {frmnotafiscal_importacupom},
  produto_serial_saida in '..\FNTS_Gerencial\fnts\produto_serial_saida.pas' {frmproduto_serial_saida},
  xloc_cst in '..\FNTS_Gerencial\fnts\xloc_cst.pas' {frmxloc_cst},
  xloc_cidade in '..\FNTS_Gerencial\fnts\xloc_cidade.pas' {frmxloc_cidade},
  cidade in '..\FNTS_Gerencial\fnts\cidade.pas' {frmCidade},
  venda_item_2 in '..\FNTS_Gerencial\fnts\venda_item_2.pas' {frmvenda_item_2},
  formapgto in '..\FNTS_Gerencial\fnts\formapgto.pas' {frmFormaPgto},
  cor in '..\FNTS_Gerencial\fnts\cor.pas' {frmcor},
  fornecedor_codigo in '..\FNTS_Gerencial\fnts\fornecedor_codigo.pas' {frmfornecedor_codigo},
  duplicata_impressao in '..\FNTS_Gerencial\fnts\duplicata_impressao.pas' {frmDuplicata_Impressao},
  Lista_ABC_Marca_Grupo in '..\FNTS_Gerencial\fnts\Lista_ABC_Marca_Grupo.pas' {frmLista_ABC_Marca_Grupo},
  importa_nfe in '..\FNTS_Gerencial\fnts\importa_nfe.pas' {frmimporta_nfe},
  contrato_reserva in '..\FNTS_Gerencial\fnts\contrato_reserva.pas' {frmContrato_reserva},
  prevenda_cliente in '..\FNTS_Gerencial\fnts\prevenda_cliente.pas' {frmprevenda_cliente},
  fluxo_caixa in '..\FNTS_Gerencial\fnts\fluxo_caixa.pas' {frmFluxo_Caixa},
  DRE in '..\FNTS_Gerencial\fnts\DRE.pas' {frmDRE},
  lista_frete in '..\FNTS_Gerencial\fnts\lista_frete.pas' {frmlista_frete},
  status in '..\FNTS_Gerencial\fnts\status.pas' {frmStatus},
  nfe_legenda in '..\FNTS_Gerencial\fnts\nfe_legenda.pas' {frmNFE_legenda},
  email in '..\FNTS_Gerencial\fnts\email.pas',
  mensagem in '..\FNTS_Gerencial\fnts\mensagem.pas' {frmmensagem},
  produto_validade in '..\FNTS_Gerencial\fnts\produto_validade.pas' {frmproduto_validade},
  produto_grade in '..\FNTS_Gerencial\fnts\produto_grade.pas' {frmproduto_grade},
  venda_reimpressao in '..\FNTS_Gerencial\fnts\venda_reimpressao.pas' {frmvenda_reimpressao},
  webcam2 in '..\FNTS_Gerencial\fnts\webcam2.pas' {frmwebcam2},
  CEST in '..\FNTS_Gerencial\fnts\CEST.pas' {frmCEST},
  xloc_csosn in '..\FNTS_Gerencial\fnts\xloc_csosn.pas' {frmxloc_csosn},
  entrada in '..\FNTS_Gerencial\fnts\entrada.pas' {frmentrada},
  os_item_2 in '..\FNTS_Gerencial\fnts\OS\os_item_2.pas' {frmOS_item_2},
  OpFaturar in '..\FNTS_Gerencial\fnts\OpFaturar.pas' {frmOpFaturar},
  sobre in '..\FNTS_Comuns\sobre.pas' {Form_sobre},
  xloc_cnae in '..\FNTS_Gerencial\fnts\xloc_cnae.pas' {frmxloc_cnae},
  OpNatureza in '..\FNTS_Gerencial\fnts\OpNatureza.pas' {frmOpNatureza},
  historico in '..\FNTS_Gerencial\fnts\historico.pas' {frmHistorico},
  UFuncoes in '..\FNTS_Gerencial\fnts\UFuncoes.pas',
  daruma_300 in '..\FNTS_Gerencial\fnts\daruma_300.pas',
  senha in '..\FNTS_Comuns\senha.pas' {frmsenha},
  orcamento_grade in '..\FNTS_Gerencial\fnts\orcamento_grade.pas' {frmorcamento_grade},
  orcamento_serial in '..\FNTS_Gerencial\fnts\orcamento_serial.pas' {frmOrcamento_serial},
  formas_pgto in '..\FNTS_Gerencial\fnts\formas_pgto.pas' {frmFormas},
  os_item_3 in '..\FNTS_Gerencial\fnts\os_item_3.pas' {frmOS_item},
  Vcl.Themes,
  Vcl.Styles,
  veiculo_novo_cte in '..\FNTS_Gerencial\fnts\veiculo_novo_cte.pas' {frmVeiculo_novo},
  msg_Operador in '..\FNTS_Gerencial\fnts\msg_Operador.pas' {frmMsg_Operador},
  tabela_preco in '..\FNTS_Gerencial\fnts\tabela_preco.pas' {frm_tb_preco},
  Unit_ativar in '..\FNTS_Comuns\Unit_ativar.pas' {Form_ativar},
  Ncm in '..\FNTS_Gerencial\fnts\Ncm.pas' {frmNcm},
  LockApplicationInterface in '..\FNTS_Comuns\LockApplicationInterface.pas' {Bloqueio},
  ecf in '..\FNTS_Gerencial\fnts\ecf.pas',
  ecf_cupom in '..\FNTS_Gerencial\fnts\ecf_cupom.pas' {frmecf_cupom},
  ecf_download in '..\FNTS_Gerencial\fnts\ecf_download.pas' {frmecf_download},
  ECF_REDUCAO in '..\FNTS_Gerencial\fnts\ECF_REDUCAO.pas' {FRMECF_REDUCAO},
  ecf_reducao_menu in '..\FNTS_Gerencial\fnts\ecf_reducao_menu.pas' {frmecf_reducao_menu},
  ecf_registro60 in '..\FNTS_Gerencial\fnts\ecf_registro60.pas' {frmecf_registro60},
  ecf_texto in '..\FNTS_Gerencial\fnts\ecf_texto.pas' {frmecf_texto},
  ecfs in '..\FNTS_Gerencial\fnts\ecfs.pas' {frmecf},
  ecfserver in '..\FNTS_Gerencial\fnts\ecfserver.pas' {frmecfserver},
  lista_ecf_reducao in '..\FNTS_Gerencial\fnts\lista_ecf_reducao.pas' {frmlista_ecf_reducao},
  transf_dados in '..\FNTS_Gerencial\fnts\transf_dados.pas' {frmtransf_dados},
  form_ativacaoicloud in '..\FNTS_Gerencial\fnts\form_ativacaoicloud.pas' {Form_ativacao},
  loc_conhecimento in '..\FNTS_Gerencial\fnts\loc_conhecimento.pas' {frmloc_conhecimento},
  LoginWindow_U in '..\FNTS_Comuns\LoginWindow_U.pas' {frmLoginWindow},
  JustificativaInutilizacaoNFe in '..\FNTS_Comuns\JustificativaInutilizacaoNFe.pas' {frmJustificativaInutilizacaoNFe},
  ResultadoWebService in '..\FNTS_Comuns\ResultadoWebService.pas' {frmResultadoWebService},
  senha_caixa in '..\FNTS_Comuns\senha_caixa.pas' {frmsenha_caixa},
  Texto in '..\FNTS_Comuns\Texto.pas' {frmTexto},
  loc_paises in '..\FNTS_Gerencial\fnts\loc_paises.pas' {frmloc_paises},
  chavenfe_importar in '..\FNTS_Gerencial\fnts\chavenfe_importar.pas' {frmchavenfe_importar},
  ConversaoUnidade in '..\FNTS_Gerencial\fnts\ConversaoUnidade.pas' {frmConversaoUnidade},
  PartilhaICMS in '..\FNTS_Gerencial\fnts\PartilhaICMS.pas' {frmPartilhaICMS},
  TextoCartaCobranca in '..\FNTS_Gerencial\fnts\TextoCartaCobranca.pas' {frmTextoCartaCobranca},
  ListaNfeBaixar in '..\FNTS_Gerencial\fnts\ListaNfeBaixar.pas' {frmListaNfeBaixar},
  ItensOrcamento in '..\FNTS_Gerencial\fnts\ItensOrcamento.pas' {frmItensOrcamento},
  AlteraItemVenda in '..\FNTS_Gerencial\fnts\AlteraItemVenda.pas' {frmAlteraItemVenda},
  RetornaEndereco in '..\FNTS_Gerencial\fnts\RetornaEndereco.pas' {frmRetornaEndereco},
  ConsultaCPF in '..\FNTS_Gerencial\fnts\ConsultaCPF.pas' {frmConsultaCPF},
  ConsultaCNPJ in '..\FNTS_Gerencial\fnts\ConsultaCNPJ.pas' {frmConsultaCNPJ};

{$R *.res}

var
  HprevHist: HWND;
begin
  Application.Initialize;
  frmsplash := Tfrmsplash.Create(Application);
  frmsplash.show;
  frmsplash.Update;
  Application.Title := 'TALOS 1.0.0.0';
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(Tfrmmodulo, frmmodulo);
  Application.CreateForm(Tfrmsplash, frmsplash);
  Application.CreateForm(TForm_ativar, Form_ativar);
  Application.CreateForm(TfrmPartilhaICMS, frmPartilhaICMS);
  Application.CreateForm(TfrmTextoCartaCobranca, frmTextoCartaCobranca);
  Application.CreateForm(TfrmListaNfeBaixar, frmListaNfeBaixar);
  Application.CreateForm(TfrmItensOrcamento, frmItensOrcamento);
  Application.CreateForm(TfrmAlteraItemVenda, frmAlteraItemVenda);
  Application.CreateForm(TfrmRetornaEndereco, frmRetornaEndereco);
  Application.CreateForm(TfrmConsultaCPF, frmConsultaCPF);
  Application.CreateForm(TfrmConsultaCNPJ, frmConsultaCNPJ);
  application.ProcessMessages;
  frmsplash.Close;
  FreeAndNil(frmsplash);
  Application.Run;
end.
